name: 'Terraform setup and plan'
description: 'Setup Terraform and create plan artifact in S3'
inputs:
  terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
  terraform_version:
    description: 'Terraform Version'
    required: true
  PAT:
    description: 'GitHub token for auth'
    required: true
  pr_id:
    description: 'Pull request ID'
    required: true
  s3_bucket_name:
    description: 'S3 bucket name'
    required: true
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_region:
    description: 'AWS Region'
    required: true
  tf_var_env:
    description: 'Optional Terraform environment'
    required: false
  s3_key_date:
    description: 'Optional date prefix for S3 key (YYYY/MM format)'
    required: false
  backend_config_file:
    description: 'Optional backend config file path relative to the terraform directory'
    required: false
  plan_key:
    description: 'Optional explicit S3 object key for the plan file (include tfplan filename)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      env:
        TF_VAR_env: ${{ inputs.tf_var_env }}
        BACKEND_CONFIG_FILE: ${{ inputs.backend_config_file }}
      run: |
        set -e
        BACKEND_FILE="${BACKEND_CONFIG_FILE}"
        if [ -z "$BACKEND_FILE" ]; then
          if [ -n "$TF_VAR_env" ]; then
            BACKEND_FILE="env/backend_s3_${TF_VAR_env}.hcl"
          else
            BACKEND_FILE="env/backend_s3.hcl"
          fi
        fi
        terraform init --backend-config="$BACKEND_FILE"

    - name: Terraform Plan
      id: plan
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      env:
        TF_VAR_env: ${{ inputs.tf_var_env }}
        TF_VAR_aws_access_key_id: ${{ inputs.aws_access_key_id }}
        TF_VAR_aws_secret_access_key: ${{ inputs.aws_secret_access_key }}
        TF_VAR_aws_region: ${{ inputs.aws_region }}
      run: |
        set -e
        terraform plan -out=tfplan

    - name: Upload Plan to S3
      shell: bash
      env:
        PLAN_KEY: ${{ inputs.plan_key }}
        TF_VAR_env: ${{ inputs.tf_var_env }}
        S3_KEY_DATE: ${{ inputs.s3_key_date }}
        PR_ID: ${{ inputs.pr_id }}
        S3_BUCKET_NAME: ${{ inputs.s3_bucket_name }}
      run: |
        if [ -n "$PLAN_KEY" ]; then
          S3_KEY="$PLAN_KEY"
        else
          KEY="$PR_ID"
          if [ -n "$TF_VAR_env" ]; then
            KEY="$KEY-$TF_VAR_env"
          fi
          KEY="$KEY-tfplan"

          if [ -n "$S3_KEY_DATE" ]; then
            S3_KEY="$S3_KEY_DATE/$KEY"
          else
            S3_KEY="$KEY"
          fi
        fi

        aws s3 cp "${{ inputs.terraform_directory }}/tfplan" "s3://$S3_BUCKET_NAME/$S3_KEY"

