# .github/apply/action.yml

name: "Terraform setup and apply"
description: "Applies a terraform plan file from S3"
inputs:
  terraform_directory: 
    description: 'Directory that holds Terraform code'
    required: true
  terraform_version: 
    description: 'Terraform Version'
    required: true
  PAT: 
    description: 'GitHub token for authentication'
    required: true
  pr_id:
    description: 'Pull request ID or commit SHA'
    required: true
  s3_bucket_name:
    description: 'S3 bucket name for plan artifacts'
    required: true
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_region:
    description: 'AWS Region'
    required: true
  tf_var_env:
    description: 'Terraform environment (dev/prod)'
    required: false
  s3_key_date:
    description: 'Date prefix for S3 key (YYYY/MM format)'
    required: false
  backend_config_file:
    description: 'Backend config file path relative to terraform_directory (e.g., "backend.dev.hcl"). If not provided, defaults to env/backend_s3_${env}.hcl'
    required: false
  plan_key:
    description: 'Explicit S3 object key for the plan file (overrides default key generation)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Terraform Init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      env:
        TF_VAR_env: ${{ inputs.tf_var_env }}
        BACKEND_CONFIG_FILE: ${{ inputs.backend_config_file }}
      run: |
        set -Eeuo pipefail
        BACKEND_FILE="${BACKEND_CONFIG_FILE}"
        if [ -z "$BACKEND_FILE" ]; then
          if [ -n "$TF_VAR_env" ]; then
            BACKEND_FILE="env/backend_s3_${TF_VAR_env}.hcl"
          else
            BACKEND_FILE="env/backend_s3.hcl"
          fi
        fi
        echo "Using backend config: $BACKEND_FILE"
        terraform init -no-color --backend-config="$BACKEND_FILE"

    - name: Download Plan from S3
      shell: bash
      env:
        TF_VAR_env: ${{ inputs.tf_var_env }}
        PLAN_KEY: ${{ inputs.plan_key }}
        S3_KEY_DATE: ${{ inputs.s3_key_date }}
        PR_ID: ${{ inputs.pr_id }}
      run: |
        set -Eeuo pipefail
        if [ -n "$PLAN_KEY" ]; then
          S3_KEY="$PLAN_KEY"
        else
          KEY="$PR_ID"
          if [ -n "$TF_VAR_env" ]; then
            KEY="$KEY-$TF_VAR_env"
          fi
          KEY="$KEY-tfplan"
          if [ -n "$S3_KEY_DATE" ]; then
            S3_KEY="$S3_KEY_DATE/$KEY"
          else
            S3_KEY="$KEY"
          fi
        fi
        echo "Downloading plan from s3://${{ inputs.s3_bucket_name }}/$S3_KEY"
        aws s3 cp "s3://${{ inputs.s3_bucket_name }}/$S3_KEY" "${{ inputs.terraform_directory }}/tfplan" --only-show-errors

    - name: Terraform Apply
      id: apply
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      env:
        TF_VAR_env: ${{ inputs.tf_var_env }}
        TF_VAR_aws_access_key_id: ${{ inputs.aws_access_key_id }}
        TF_VAR_aws_secret_access_key: ${{ inputs.aws_secret_access_key }}
        TF_VAR_aws_region: ${{ inputs.aws_region }}
      run: |
        set -Eeuo pipefail
        echo "Applying terraform plan..."
        terraform apply -input=false tfplan
